# Testing the Deterministic Bank Statement Parser

This notebook demonstrates how to use the deterministic parser to extract transaction data from DBS bank statement PDFs.

## Features Demonstrated
- Basic parsing and extraction
- Confidence scoring and warnings
- Transaction data structure
- Validation against known values
- Visual inspection of extracted data

## Setup and Imports

In [1]:
import sys
import json
from pathlib import Path
import pandas as pd

# Add src to path so we can import our parser
sys.path.insert(0, str(Path('..').resolve()))

from src.parsers.deterministic_parser import DeterministicBankStatementParser

## 1. Basic Parsing Example

Let's parse the DBS Singapore bank statement and examine the results.

In [2]:
# Initialize the parser
parser = DeterministicBankStatementParser()

# Path to the PDF
pdf_path = "../resources/statements/702490847-DBS-Singapore-Bank-Statement.pdf"

# Parse the document
result = parser.parse(pdf_path)

# Display basic results
print(f"Success: {result.success}")
print(f"Confidence: {result.confidence:.2%}")
print(f"Transactions Extracted: {len(result.data)}")
print(f"Warnings: {len(result.warnings)}")

if result.abort_reason:
    print(f"Abort Reason: {result.abort_reason}")

Success: True
Confidence: 100.00%
Transactions Extracted: 117
Warnings: 2

## 2. Examine Warnings

The parser generates warnings for anomalies or issues encountered during parsing.

In [3]:
print("Warnings:")
print("=" * 60)
for i, warning in enumerate(result.warnings, 1):
    print(f"{i}. {warning}")

Warnings:
============================================================
1. Could not find transaction table on page 1
2. Could not find transaction table on page 13

## 3. View Sample Transactions

Let's examine the first few transactions to understand the data structure.

In [4]:
# Display first 5 transactions
print("First 5 Transactions:")
print("=" * 100)

for i, txn in enumerate(result.data[:5], 1):
    print(f"\n[Transaction {i}]")
    print(f"  Date:        {txn['date']}")
    print(f"  Description: {txn['description'][:60]}..." if len(txn['description']) > 60 else f"  Description: {txn['description']}")
    print(f"  Withdrawal:  {txn['withdrawal'] if txn['withdrawal'] else '-'}")
    print(f"  Deposit:     {txn['deposit'] if txn['deposit'] else '-'}")
    print(f"  Balance:     {txn['balance']}")
    print(f"  Page:        {txn['page']}")

First 5 Transactions:
====================================================================================================

[Transaction 1]
  Date:        01/01/2022
  Description: Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA SI NG 01DEC 46...
  Withdrawal:  20.0
  Deposit:     -
  Balance:     7980.0
  Page:        2

[Transaction 2]
  Date:        01/01/2022
  Description: Advice FAST Payment / Receipt INCOMING PAYNOW REF 8441833 FR...
  Withdrawal:  4.4
  Deposit:     -
  Balance:     7975.6
  Page:        2

[Transaction 3]
  Date:        02/01/2022
  Description: Point-of-Sale Transaction 57741465, DHEEN RESTAURANT NETS
  Withdrawal:  5.0
  Deposit:     -
  Balance:     7970.6
  Page:        2

[Transaction 4]
  Date:        02/12/2022
  Description: Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA SI NG 30NOV 46...
  Withdrawal:  2.2
  Deposit:     -
  Balance:     7968.4
  Page:        2

[Transaction 5]
  Date:        02/01/2022
  Description: Advice FAST Payment / Receipt INCOMING PAYNOW REF 7407075 FR...
  Withdrawal:  -
  Deposit:     125.0
  Balance:     8093.4
  Page:        2

## 4. Convert to Pandas DataFrame

For easier analysis and manipulation, convert the transaction data to a pandas DataFrame.

In [5]:
# Create DataFrame
df = pd.DataFrame(result.data)

# Display basic info
print(f"Total Transactions: {len(df)}")
print(f"\nDataFrame Info:")
print(df.info())

# Display first few rows
print("\nFirst 10 Transactions:")
df.head(10)

Total Transactions: 117

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         117 non-null    object
 1   description  117 non-null    object
 2   withdrawal   90 non-null     float64
 3   deposit      31 non-null     float64
 4   balance      117 non-null    float64
 5   page         117 non-null    int64
dtypes: float64(3), int64(1), object(2)
memory usage: 5.6+ KB
None

First 10 Transactions:

,date,description,withdrawal,deposit,balance,page
0,01/01/2022,Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA ...,20.0,NaN,7980.0,2
1,01/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,4.4,NaN,7975.6,2
2,02/01/2022,"Point-of-Sale Transaction 57741465, DHEEN REST...",5.0,NaN,7970.6,2
3,02/12/2022,Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA ...,2.2,NaN,7968.4,2
4,02/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,125.0,8093.4,2
5,04/01/2022,"Point-of-Sale Transaction 52880148A 58552358,M...",6.1,NaN,8087.3,2
6,04/01/2022,Debit Card Transaction / MR-8500180-3 MANADR S...,8.0,NaN,8077.1,2
7,04/01/2022,"Point-of-Sale Transaction No: 57741465,BAHUBAL...",3.5,2673.0,8073.6,2
8,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,NaN,11338.6,2
9,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,NaN,11338.6,2

## 5. Data Analysis

Perform basic analysis on the extracted transactions.

In [6]:
# Summary statistics
print("Transaction Statistics:")
print("=" * 60)
print(f"Total Transactions:     {len(df)}")
print(f"Transactions with Withdrawals: {df['withdrawal'].notna().sum()}")
print(f"Transactions with Deposits:    {df['deposit'].notna().sum()}")
print(f"\nTotal Withdrawals:  SGD {df['withdrawal'].sum():,.2f}")
print(f"Total Deposits:     SGD {df['deposit'].sum():,.2f}")
print(f"Net Change:         SGD {df['deposit'].sum() - df['withdrawal'].sum():,.2f}")

# Opening and closing balances
opening_balance = df.iloc[0]['balance'] + (df.iloc[0]['withdrawal'] or 0) - (df.iloc[0]['deposit'] or 0)
closing_balance = df.iloc[-1]['balance']

print(f"\nOpening Balance:    SGD {opening_balance:,.2f}")
print(f"Closing Balance:    SGD {closing_balance:,.2f}")
print(f"Actual Change:      SGD {closing_balance - opening_balance:,.2f}")

Transaction Statistics:
============================================================
Total Transactions:     117
Transactions with Withdrawals: 90
Transactions with Deposits:    31

Total Withdrawals:  SGD 8,937.18
Total Deposits:     SGD 6,085.04
Net Change:         SGD -2,852.14

Opening Balance:    SGD nan
Closing Balance:    SGD 9,754.64
Actual Change:      SGD nan

## 6. Filter and Search Transactions

Examples of how to filter and search through transactions.

In [7]:
# Find all deposits
deposits = df[df['deposit'].notna()]
print(f"Deposit Transactions ({len(deposits)}):")
print("=" * 100)
deposits[['date', 'description', 'deposit', 'balance']]

Deposit Transactions (31):
====================================================================================================

,date,description,deposit,balance
4,02/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,125.00,8093.40
7,04/01/2022,"Point-of-Sale Transaction No: 57741465,BAHUBAL...",2673.00,8073.60
20,07/01/2022,Debit Card Transaction No. NET*DHEEN RESTAURAN...,0.02,11208.87
21,07/01/2022,Debit Card Transaction No. NET*DHEEN RESTAURAN...,0.02,11208.87
29,11/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,120.00,11153.93
37,15/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,85.00,11173.98
38,15/01/2022,Advice FAST Payment / Receipt MR-8500180-3 / I...,90.00,11263.98
42,16/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,130.00,11384.78
46,17/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,85.00,11447.18
50,18/01/2022,Advice FAST Payment / Receipt Reg GST INCOMING...,50.00,11404.28
56,19/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,90.00,11346.83
59,19/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,150.00,11258.83
60,19/01/2022,Advice FAST Payment / Receipt MOHAN INTERN 11-...,539.00,11797.83
63,19/01/2022,Advice FAST Payment / Receipt Co. INCOMING PAY...,20.00,11243.52
64,19/01/2022,Advice FAST Payment / Receipt Co. INCOMING PAY...,20.00,11243.52
66,20/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,90.00,11133.52
67,20/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,65.00,11198.52
74,23/01/2022,Advice FAST Payment / Receipt Reg GST INCOMING...,85.00,110150.27
77,23/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,10.00,11080.27
83,24/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,15.00,11052.77
84,24/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,20.00,11072.77
88,26/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,80.00,11062.77
89,26/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,10.00,11072.77
90,27/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,200.00,11272.77
92,27/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,300.00,11372.77
94,27/01/2022,Advice FAST Payment / Receipt MOHAN INTERN 18-...,620.00,11792.77
95,27/01/2022,Advice FAST Payment / Receipt Biz INCOMING PAY...,10.00,11802.77
96,28/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,200.00,12002.77
103,28/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,150.00,12103.72
105,28/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,33.00,11086.72
114,31/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,20.00,11054.64

In [8]:
# Find large withdrawals (> 100 SGD)
large_withdrawals = df[df['withdrawal'] > 100]
print(f"Large Withdrawals > SGD 100 ({len(large_withdrawals)}):")
print("=" * 100)
large_withdrawals[['date', 'description', 'withdrawal', 'balance']]

Large Withdrawals > SGD 100 (13):
====================================================================================================

,date,description,withdrawal,balance
8,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,11338.60
9,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,11338.60
10,06/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,225.0,11113.60
14,06/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,2450.0,13543.72
17,06/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,258.0,11260.72
29,11/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,260.0,11153.93
58,19/01/2022,"Point-of-Sale Transaction 57741465,SMARTCITY NETS",148.0,11108.83
60,19/01/2022,Advice FAST Payment / Receipt MOHAN INTERN 11-...,539.0,11797.83
65,19/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.0,11043.52
91,27/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.0,11072.77
93,27/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.0,11172.77
115,31/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,1300.0,9754.64
116,31/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,1300.0,9754.64

In [9]:
# Search for specific keywords in description
keyword = "PAYNOW"  # Change this to search for different keywords
matching_txns = df[df['description'].str.contains(keyword, case=False, na=False)]

print(f"Transactions containing '{keyword}' ({len(matching_txns)}):")
print("=" * 100)
matching_txns[['date', 'description', 'withdrawal', 'deposit', 'balance']]

Transactions containing 'PAYNOW' (47):
====================================================================================================

,date,description,withdrawal,deposit,balance
1,01/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,4.40,NaN,7975.60
4,02/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,125.0,8093.40
8,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.00,NaN,11338.60
9,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.00,NaN,11338.60
10,06/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,225.00,NaN,11113.60
11,06/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,5.00,NaN,11108.60
14,06/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,2450.00,NaN,13543.72
17,06/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,258.00,NaN,11260.72
24,08/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,100.00,NaN,11057.23
29,11/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,260.00,120.0,11153.93
37,15/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,85.0,11173.98
38,15/01/2022,Advice FAST Payment / Receipt MR-8500180-3 / I...,NaN,90.0,11263.98
42,16/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,130.0,11384.78
46,17/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,85.0,11447.18
49,17/01/2022,"Point-of-Sale Transaction 57741465,DHEEN RESTA...",6.20,NaN,11416.68
50,18/01/2022,Advice FAST Payment / Receipt Reg GST INCOMING...,NaN,50.0,11404.28
51,18/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,90.00,NaN,11314.28
52,18/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,90.00,NaN,11314.28
56,19/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,90.0,11346.83
57,19/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,90.00,NaN,11256.83
59,19/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,150.0,11258.83
60,19/01/2022,Advice FAST Payment / Receipt MOHAN INTERN 11-...,539.00,539.0,11797.83
62,19/01/2022,Advice FAST Payment / Receipt 196800306E PAYNO...,8.31,NaN,11223.52
63,19/01/2022,Advice FAST Payment / Receipt Co. INCOMING PAY...,NaN,20.0,11243.52
64,19/01/2022,Advice FAST Payment / Receipt Co. INCOMING PAY...,NaN,20.0,11243.52
65,19/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.00,NaN,11043.52
66,20/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,90.0,11133.52
67,20/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,65.0,11198.52
73,22/01/2022,Debit Card Transaction No. MANADR SI NG 20DEC ...,8.00,NaN,11082.37
74,23/01/2022,Advice FAST Payment / Receipt Reg GST INCOMING...,NaN,85.0,110150.27
77,23/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,10.0,11080.27
82,24/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,1.00,NaN,11037.77
84,24/01/2022,Advice Funds Transfer SEND BACK FROM PAYLAH! :...,10.00,20.0,11072.77
85,26/01/2022,Advice FAST Payment / Receipt No: PAYNOW TRANS...,80.00,NaN,11062.77
86,26/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,80.00,NaN,10982.77
87,26/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,80.00,NaN,10982.77
90,27/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,200.0,11272.77
91,27/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.00,NaN,11072.77
92,27/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,300.0,11372.77
93,27/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,200.00,NaN,11172.77
95,27/01/2022,Advice FAST Payment / Receipt Biz INCOMING PAY...,NaN,10.0,11802.77
96,28/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,200.0,12002.77
103,28/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,150.0,12103.72
104,28/01/2022,"Advice FAST Payment / Receipt 1,050.00 PAYNOW ...",NaN,NaN,11053.72
105,28/01/2022,Advice FAST Payment / Receipt PAYNOW TRANSFER ...,NaN,33.0,11086.72
115,31/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,1300.00,NaN,9754.64
116,31/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,1300.00,NaN,9754.64

## 7. Validate Balance Continuity

Check that each transaction's balance follows correctly from the previous balance.

In [10]:
# Validate balance arithmetic
discrepancies = []

for i in range(1, len(df)):
    prev_balance = df.iloc[i-1]['balance']
    curr_balance = df.iloc[i]['balance']
    withdrawal = df.iloc[i]['withdrawal'] or 0
    deposit = df.iloc[i]['deposit'] or 0
    
    expected_balance = prev_balance - withdrawal + deposit
    
    # Allow for small floating point differences
    if abs(expected_balance - curr_balance) > 0.01:
        discrepancies.append({
            'index': i,
            'date': df.iloc[i]['date'],
            'expected': expected_balance,
            'actual': curr_balance,
            'difference': curr_balance - expected_balance
        })

if discrepancies:
    print(f"Found {len(discrepancies)} balance discrepancies:")
    for disc in discrepancies:
        print(f"  Transaction {disc['index']} ({disc['date']}): Expected {disc['expected']:.2f}, Got {disc['actual']:.2f}")
else:
    print("✓ All balance calculations are consistent!")

Found 6 balance discrepancies:
  Transaction 7 (04/01/2022): Expected 10746.60, Got 8073.60
  Transaction 20 (07/01/2022): Expected 11208.89, Got 11208.87
  Transaction 21 (07/01/2022): Expected 11194.39, Got 11208.87
  Transaction 29 (11/01/2022): Expected 10893.93, Got 11153.93
  Transaction 60 (19/01/2022): Expected 11258.83, Got 11797.83
  Transaction 84 (24/01/2022): Expected 11062.77, Got 11072.77

## 8. Export to JSON

Save the extracted data to a JSON file for further processing.

In [11]:
# Create output dictionary
output_data = {
    "success": result.success,
    "confidence": result.confidence,
    "warnings": result.warnings,
    "transaction_count": len(result.data),
    "data": result.data
}

# Save to file
output_path = "../extracted_data_notebook.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(output_data, f, indent=2, ensure_ascii=False)

print(f"Data exported to: {output_path}")

Data exported to: ../extracted_data_notebook.json

## 9. Experiment: Parse Specific Pages

You can modify the parser to test specific scenarios or pages.

In [12]:
# Example: Get transactions from page 2 only
page_2_txns = df[df['page'] == 2]

print(f"Transactions on Page 2: {len(page_2_txns)}")
print("=" * 100)
page_2_txns

Transactions on Page 2: 10
====================================================================================================

,date,description,withdrawal,deposit,balance,page
0,01/01/2022,Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA ...,20.0,NaN,7980.0,2
1,01/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,4.4,NaN,7975.6,2
2,02/01/2022,"Point-of-Sale Transaction 57741465, DHEEN REST...",5.0,NaN,7970.6,2
3,02/12/2022,Debit Card Transaction 7-ELEVEN-KEMBANGAN PLA ...,2.2,NaN,7968.4,2
4,02/01/2022,Advice FAST Payment / Receipt INCOMING PAYNOW ...,NaN,125.0,8093.4,2
5,04/01/2022,"Point-of-Sale Transaction 52880148A 58552358,M...",6.1,NaN,8087.3,2
6,04/01/2022,Debit Card Transaction / MR-8500180-3 MANADR S...,8.0,NaN,8077.1,2
7,04/01/2022,"Point-of-Sale Transaction No: 57741465,BAHUBAL...",3.5,2673.0,8073.6,2
8,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,NaN,11338.6,2
9,05/01/2022,Advice FAST Payment / Receipt Co. DBS PAYNOW T...,200.0,NaN,11338.6,2

## 10. Custom Analysis Playground

Use this cell to experiment with your own queries and analysis.

In [13]:
# Your custom analysis here

# Example: Group by date and sum amounts
# df['date_only'] = pd.to_datetime(df['date'], format='%d/%m/%Y')
# daily_summary = df.groupby('date_only').agg({
#     'withdrawal': 'sum',
#     'deposit': 'sum'
# })
# print(daily_summary)